name: Playwright Tests with Pytest

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
        # Include any other dependencies your project needs like playwright
        pip3 install playwright
        # Make sure to call playwright install to install the necessary browser binaries
        playwright install
        # Include other project dependencies...
    - name: Run tests with pytest
      run: |
        make sanity-tests